import Provider from "@/provider/contextProvider";
import "../globals.css";
import DashNavbar from "@/components/dashboard/das-navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="lg:flex justify-center space-y-5 lg:space-y-0 ">
            <div className="w-1/5">
              <DashNavbar />
            </div>
            <div className="mx-auto w-4/5 px-2">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
